### ISSUE TITLE
Could you add multiple gpu support to iqn script?

### ISSUE THREAD

**Issue by THSWind** [BY571/IQN-and-Extensions#2]
Hello, Dittert，

I'm sorry to disturb you again. I'm very interested in your work. Could you tell me how to add multiple gpu support to this iqn script? I tried it( just like the following code), but it occurs some errors.

```
device = torch.device("cuda:2" if torch.cuda.is_available() else "cpu")
if torch.cuda.device_count() > 1:  # by thswind
    agent = torch.nn.DataParallel(agent, device_ids=[2,3,4])  # by thswind
agent.to(device)  # by thswind
```

I wish you you are willing to help me, I want to stand on the shoulder of you like stand on the shoulder of  giant.

**Comment by BY571** [comment]
Until now I have never worked with multi GPU. what type of error does occur?

**Comment by THSWind** [comment]
@BY571 It seems no matter how I write it, it just use one gpu. 
I have write it according to the documentation of pytorch about multi gpu. but because it seems not so directly at here.  
------------------------------------
the model is in the model.py,
agent.py import this model
run.py import agent.py and instantiation it.
-------------------------------------
So, if I change the code directly in run.py like this 
https://github.com/BY571/IQN-and-Extensions/issues/2#issue-683425320

it's error message shows that 

- AttributeError:  'IQN_Agent' object has no attribute 'to'

- AttributeError: 'DataParallel' object has no attribute 'act'

it's error message just like  which i have list above.

**Comment by BY571** [comment]
Hey again, sry since I haven't worked with multi gpu I can't really help you here.

- first error message looks like something is wrong with the .to(device) method.
- about the second I have no clue

hope you already figured it out?
