### ISSUE TITLE
meaning of taus in calculating quantile loss?

### ISSUE THREAD

**Issue by SHITIANYU-hue** [BY571/IQN-and-Extensions#5]
In the [notebook implementation](https://github.com/BY571/IQN-and-Extensions/blob/master/IQN-DQN.ipynb). I am a little bit confused about this line:
![image](https://user-images.githubusercontent.com/38762389/95699609-ea03e300-0c12-11eb-8caf-363a3f36db1d.png)

**Comment by BY571** [comment]
@SHITIANYU-hue  why are you confused? 

Here the quantile Huber loss: 
![image](https://user-images.githubusercontent.com/29492081/95706153-5d7b1400-0c56-11eb-80be-7ff0d63ee5ed.png)

**Comment by SHITIANYU-hue** [comment]
Thanks! And why you need to fix the TD error's shape as 8?  Does that come from n_tau?
![image](https://user-images.githubusercontent.com/38762389/95752688-6677df80-0c6e-11eb-83fb-002938c42217.png)

**Comment by BY571** [comment]
the screenshot is from the notebook-version? 
yes, td_error has the shape of (batch_size, n_tau, n_tau)
